language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=master
    - APP=files_texteditor
    - TC=other
    - SRV_HOST_NAME=owncloud
    - SRV_HOST_PORT=8889
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

addons:
  apt: &common_apt
    packages:
    - libxml2-utils
  hosts: &common_hosts
    - owncloud

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP

install:
  - sh -c "if [ '$TC' = 'selenium' ]; then bash tests/travis/install.sh $DB; fi"

before_script:
  - sh -c "if [ '$TC' = 'selenium' ]; then bash tests/travis/start_php_dev_server.sh; fi"

script:
  # Run UI tests
  - sh -c "if [ '$TC' = 'selenium' ]; then bash apps/$APP/tests/travis/start_ui_tests.sh; fi"
  # Test lint
  - sh -c "if [ '$TC' = 'other' ]; then bash apps/$APP/tests/travis/start_php_lint_tests.sh; fi"
  # Run phpunit tests
  - sh -c "if [ '$TC' = 'other' ]; then bash apps/$APP/tests/travis/start_php_unit_tests.sh; fi"
  # Create coverage report
  - sh -c "if [ '$TC' = 'other' ]; then bash apps/$APP/tests/travis/start_coverage_report.sh; fi"

matrix:
  include:
    - php: 5.6
      env: DB=sqlite TC=selenium BROWSER="chrome" BROWSER_VERSION="latest" PLATFORM="Windows 10"
      addons:
        apt: *common_apt
        hosts: *common_hosts
        sauce_connect: true
  fast_finish: true
